plugins:
  - jekyll-paginate-v2

include:
  - assets/css/cusdis-theme.css

# Pagination Settings
pagination:
  permalink: '/page/:num/'
  enabled: true
  limit: 0
  per_page: 2
  sort_field: 'date'
  sort_reverse: true
  # Optional,omit or set both before and after to zero to disable. 
  # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2
  indexpage: 'diary'  